### PR TITLE
PAQ release note for 10.18.0.5 fix

### PR DESCRIPTION
**Pull request by kailol-sag**

### CODE REVIEW

**Review by BeateRixen — APPROVED** [review]

**Review by skom-sag — APPROVED** [review]

**Comment by kailol-sag** [comment]
Thanks @skom-sag , can this go live immediately?

**Comment by skom-sag** [comment]
The doc has to wait, fix isn't yet live on empower

**Comment by kailol-sag** [comment]
One more question: do we also have to copy this to the 10.17 release so that it's also visible at https://cumulocity.com/releasenotes/release-10-17-0/streaming-analytics-10-17-0/  ???

**Review by skom-sag — APPROVED** [review]

**Review by ddfourni1 — APPROVED** [review]
Looks even better now :-)

**Comment by kailol-sag** [comment]
Hi @BeateRixen , 
@ddfourni1 just told me that the fix is now public. So can you please merge this PR into develop and also into main so that the fix release note can go live? Thanks a lot :-)

**Comment by BeateRixen** [comment]
> Hi @BeateRixen , @ddfourni1 just told me that the fix is now public. So can you please merge this PR into develop and also into main so that the fix release note can go live? Thanks a lot :-)

Done

**Pull request merged**
