### PR TITLE
PAQ release note for 10.18.0.8

### PR DESCRIPTION
**Pull request by kailol-sag**

### CODE REVIEW

**Review by ddfourni1 — APPROVED** [review]
Looks okay to me.

**Review by ddfourni1 — APPROVED** [review]
looks good.

**Comment by kailol-sag** [comment]
@BeateRixen , please merge and publish this.
10.18.0.8 has not yet reached ReleaseCandidates-Published, however, we have just decided that it can be published prematurely so I have if off my todo list.

**Comment by BeateRixen** [comment]
> @BeateRixen , please merge and publish this. 10.18.0.8 has not yet reached ReleaseCandidates-Published, however, we have just decided that it can be published prematurely so I have if off my todo list.

@kailol-sag Merged, cherry-picked to main and published.

**Pull request merged**
