### PR TITLE
Release notes for OEE 1010.0.3

### PR DESCRIPTION
**Pull request by thomaswinkler**
Release notes for OEE 1010.0.3. 

Release in Jira: https://cumulocity.atlassian.net/projects/COE/versions/16129/tab/release-report-all-issues

### CODE REVIEW

**Comment by BeateRixen** [comment]
@thomaswinkler Please always branch from and merge to the develop branch, not to the main branch. Since we copied everything from c8y-docs into this new repo, I´m wondering why this is missing. Is this new content?

**Comment by thomaswinkler** [comment]
> @thomaswinkler Please always branch from and merge to the develop branch, not to the main branch. Since we copied everything from c8y-docs into this new repo, I´m wondering why this is missing. Is this new content?

Sorry about this. Yes, it is new content for OEE 1010.0.3 Fix release.

**Comment by BeateRixen** [comment]
> > @thomaswinkler Please always branch from and merge to the develop branch, not to the main branch. Since we copied everything from c8y-docs into this new repo, I´m wondering why this is missing. Is this new content?
> 
> Sorry about this. Yes, it is new content for OEE 1010.0.3 Fix release.

I cannot easily change the target branch, seems that there are too many differences (main has just recently been updated to hold the current content). Could you please create a new branch from develop and add the modified file there and create a new PR and close this one? I think that is the easiest.

**Comment by thomaswinkler** [comment]
> > > @thomaswinkler Please always branch from and merge to the develop branch, not to the main branch. Since we copied everything from c8y-docs into this new repo, I´m wondering why this is missing. Is this new content?
> > 
> > 
> > Sorry about this. Yes, it is new content for OEE 1010.0.3 Fix release.
> 
> I cannot easily change the target branch, seems that there are too many differences (main has just recently been updated to hold the current content). Could you please create a new branch from develop and add the modified file there and create a new PR and close this one? I think that is the easiest.

Sure. Will do. Thank you.

**Pull request closed without merging**
