### PR TITLE
Improvement/bugherd task 544

### PR DESCRIPTION
**Pull request by JoshuaAdemola**

### CODE REVIEW

**Comment by BeateRixen** [comment]
@JoshuaAdemola Did any developer approve this change? I don´t think that there should be files deleted?

**Comment by JoshuaAdemola** [comment]
> @JoshuaAdemola Did any developer approve this change? I don´t think that there should be files deleted?

@BeateRixen, The files were deleted in a commit made by Marlene. Some how the commit was included in my PR.

**Comment by BeateRixen** [comment]
> > @JoshuaAdemola Did any developer approve this change? I don´t think that there should be files deleted?
> 
> @BeateRixen, The files were deleted in a commit made by Marlene. Some how the commit was included in my PR.

But your PR is only 2 hours old. Did you fetch/pull before creating the PR? Could you please merge develop into your branch again? 
And how about the dev approval?

**Comment by MWindel** [comment]
@BeateRixen @JoshuaAdemola I have reverted the commit with the deleted files. I hope the issue has been solved

**Comment by JoshuaAdemola** [comment]
> @BeateRixen @JoshuaAdemola I have reverted the commit with the deleted files. I hope the issue has been solved



> @BeateRixen @JoshuaAdemola I have reverted the commit with the deleted files. I hope the issue has been solved

@MWindel Thanks, the issue has been resolved

**Comment by JoshuaAdemola** [comment]
> @BeateRixen @JoshuaAdemola I have reverted the commit with the deleted files. I hope the issue has been solved



> @BeateRixen @JoshuaAdemola I have reverted the commit with the deleted files. I hope the issue has been solved

@MWindel Thanks, the issue has been resolved

**Comment by JoshuaAdemola** [comment]
@BeateRixen Carlos approves the change. He says it should be `dlt-c8y-icon-**`

**Review by BeateRixen — APPROVED** [review]

**Pull request merged**
