### PR TITLE
Release notes re deprecated APIs wrt to time-series

### PR DESCRIPTION
**Pull request by martin-sag**

### CODE REVIEW

**Review by BeateRixen — APPROVED** [review]

**Comment by BeateRixen** [comment]
Looks good! I have done some minor changes.

**Comment by BeateRixen** [comment]
@martin-sag Shall I merge it or do you want a second approval by a developer?

**Comment by martin-sag** [comment]
Yes, I think we can merge it for 10.15, we'll add the notes separately

**Comment by BeateRixen** [comment]
@martin-sag You have added this to the 10.14 announcements, so I suppose it should go to 10.14? We should do that asap as the 10.14 announcements are already public as preview for quite some time. I will add the same text to the 10.15 announcements then.

**Pull request merged**
